version: 2.1

orbs:
  node: circleci/node@6.1.0

workflows:
  lint-and-build:
    jobs:
      - node/run:
          name: Lint
          npm-run: lint
          version: '20.10'
      - node/run:
          name: Build
          npm-run: build
          version: '20.10'
